"""
DocsQuery - Citation Validator

Validates citations generated by the LLM.

The validator performs two important checks:

1. Every citation used by the answer must exist in the
   retrieved evidence.
2. Every factual sentence must contain at least one citation.

Example evidence:

    [C1]
    Python is a programming language.

    [C2]
    Python uses indentation.

Valid answer:

    Python is a programming language. [C1]
    Python uses indentation. [C2]

Invalid answer:

    Python is a programming language. [C7]

because C7 was not provided as evidence.
"""

import re

from app.generation.context_builder import CitationContext


class CitationValidationError(Exception):
    """
    Raised when an LLM answer fails citation validation.
    """

    pass


class CitationValidator:
    """
    Validates citation references in generated answers.
    """

    # Matches:
    #
    # [C1]
    # [C2]
    # [C25]
    #
    CITATION_PATTERN = re.compile(r"\[C(\d+)\]")

    def validate(
        self,
        answer: str,
        contexts: list[CitationContext],
    ) -> None:
        """
        Validate citations in an LLM-generated answer.

        Args:
            answer:
                Generated answer from the LLM.

            contexts:
                Evidence that was supplied to the LLM.

        Raises:
            CitationValidationError:
                If the answer contains invalid citations
                or factual sentences without citations.
        """

        # ----------------------------------------------------
        # Basic validation.
        # ----------------------------------------------------

        if not answer.strip():
            raise CitationValidationError("Answer is empty.")

        if not contexts:
            raise CitationValidationError("No citation context is available.")

        # ----------------------------------------------------
        # Build the set of citation IDs that actually exist.
        #
        # Example:
        #
        # contexts:
        #   C1
        #   C2
        #
        # valid_ids:
        #   {"C1", "C2"}
        # ----------------------------------------------------

        valid_ids = {context.citation_id for context in contexts}

        # ----------------------------------------------------
        # Extract citations from the generated answer.
        # ----------------------------------------------------

        citations = self.CITATION_PATTERN.findall(answer)

        referenced_ids = {f"C{citation}" for citation in citations}

        # ----------------------------------------------------
        # Make sure the LLM did not invent a citation.
        #
        # Example:
        #
        # Evidence contains C1 and C2.
        #
        # Answer contains C99.
        #
        # C99 must be rejected.
        # ----------------------------------------------------

        unknown_ids = referenced_ids - valid_ids

        if unknown_ids:
            raise CitationValidationError(
                "Answer contains unknown citation IDs: "
                + ", ".join(sorted(unknown_ids))
            )

        # ----------------------------------------------------
        # Check that factual sentences contain citations.
        # ----------------------------------------------------

        sentences = self._split_sentences(answer)

        for sentence in sentences:
            if not self._contains_citation(sentence):
                raise CitationValidationError(
                    f"Factual sentence is missing a citation: {sentence}"
                )

    def extract_citations(
        self,
        answer: str,
    ) -> list[str]:
        """
        Extract unique citation IDs from an answer.

        The order in which citations first appear is preserved.

        Example:

            "Python [C2]. It is readable [C1]. [C2]"

        Returns:

            ["C2", "C1"]
        """

        matches = self.CITATION_PATTERN.findall(answer)

        citations: list[str] = []

        for citation in matches:
            citation_id = f"C{citation}"

            # Don't add the same citation twice.
            if citation_id not in citations:
                citations.append(citation_id)

        return citations

    def _split_sentences(
        self,
        answer: str,
    ) -> list[str]:
        """
        Split an answer into citation-aware sentences.

        A normal sentence may look like:

            Python is a language. [C1]

        We must keep [C1] attached to the sentence.

        Markdown headings are ignored.
        Empty lines are ignored.
        """

        # ----------------------------------------------------
        # Process the answer line by line first.
        # ----------------------------------------------------

        lines = answer.strip().splitlines()

        cleaned_lines: list[str] = []

        for line in lines:
            line = line.strip()

            # Ignore empty lines.
            if not line:
                continue

            # Ignore Markdown headings such as:
            #
            # ## Answer
            #
            if line.startswith("#"):
                continue

            cleaned_lines.append(line)

        # Join Markdown paragraphs into one string.
        text = " ".join(cleaned_lines)

        if not text:
            return []

        # ----------------------------------------------------
        # Split only when punctuation is followed by actual
        # sentence content.
        #
        # This prevents:
        #
        #   "Python is a language. [C1]"
        #
        # from becoming:
        #
        #   "Python is a language."
        #   "[C1]"
        #
        # The citation remains attached to the sentence.
        # ----------------------------------------------------

        sentences = re.split(
            r"(?<=[.!?])\s+(?=[A-Z0-9])",
            text,
        )

        return [sentence.strip() for sentence in sentences if sentence.strip()]

    def _contains_citation(
        self,
        sentence: str,
    ) -> bool:
        """
        Return True if a sentence contains a citation.
        """

        return bool(self.CITATION_PATTERN.search(sentence))
